-- =============================================================================
-- Soccer Analytics ML System -- PostgreSQL Schema
--
-- ID naming convention (strict throughout):
--   *_id          internal surrogate PK generated by this DB (SERIAL)
--   sb_*_id       StatsBomb source identifier
--   tm_*_id       Transfermarkt source identifier
--
-- Fix: injuries.injury_date is now NOT NULL. Previously the UNIQUE constraint
-- on (player_id, injury_date, injury_type) was ineffective when injury_date
-- was NULL because PostgreSQL does not consider NULL values equal in unique
-- constraints, allowing duplicate rows with the same player_id and injury_type
-- but NULL injury_date to insert without conflict.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- TEAMS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS teams (
    team_id         SERIAL  PRIMARY KEY,
    team_name       TEXT    NOT NULL,
    sb_team_id      INT     UNIQUE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_teams_sb ON teams (sb_team_id);


-- -----------------------------------------------------------------------------
-- PLAYERS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS players (
    player_id       SERIAL  PRIMARY KEY,
    sb_player_id    INT     UNIQUE,
    tm_player_id    INT,
    player_name     TEXT    NOT NULL,
    norm_name       TEXT,
    nationality     TEXT,
    position        TEXT,
    date_of_birth   DATE
);

CREATE INDEX IF NOT EXISTS idx_players_sb        ON players (sb_player_id);
CREATE INDEX IF NOT EXISTS idx_players_norm_name ON players (norm_name);
CREATE INDEX IF NOT EXISTS idx_players_tm        ON players (tm_player_id);


-- -----------------------------------------------------------------------------
-- STADIUMS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stadiums (
    stadium_id      SERIAL  PRIMARY KEY,
    stadium_name    TEXT    NOT NULL UNIQUE,
    stadium_lat     FLOAT,
    stadium_lng     FLOAT
);

CREATE INDEX IF NOT EXISTS idx_stadiums_name ON stadiums (stadium_name);


-- -----------------------------------------------------------------------------
-- MATCHES
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS matches (
    match_id        SERIAL  PRIMARY KEY,
    sb_match_id     INT     UNIQUE NOT NULL,
    match_date      DATE,
    home_team_id    INT     REFERENCES teams    (team_id),
    away_team_id    INT     REFERENCES teams    (team_id),
    home_score      INT,
    away_score      INT,
    competition     TEXT,
    season          TEXT,
    stadium_id      INT     REFERENCES stadiums (stadium_id)
);

CREATE INDEX IF NOT EXISTS idx_matches_date        ON matches (match_date);
CREATE INDEX IF NOT EXISTS idx_matches_competition ON matches (competition, season);
CREATE INDEX IF NOT EXISTS idx_matches_home_team   ON matches (home_team_id);
CREATE INDEX IF NOT EXISTS idx_matches_away_team   ON matches (away_team_id);
CREATE INDEX IF NOT EXISTS idx_matches_sb          ON matches (sb_match_id);
CREATE INDEX IF NOT EXISTS idx_matches_stadium     ON matches (stadium_id);


-- -----------------------------------------------------------------------------
-- WEATHER  (one row per match)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS weather (
    weather_id          SERIAL  PRIMARY KEY,
    match_id            INT     NOT NULL REFERENCES matches (match_id) ON DELETE CASCADE,
    temperature_c       FLOAT,
    humidity_pct        FLOAT,
    wind_speed_kmh      FLOAT,
    precipitation_mm    FLOAT,
    weather_condition   TEXT    CHECK (
        weather_condition IN ('clear', 'rain', 'heavy_rain', 'windy', 'cold', 'hot')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_weather_match ON weather (match_id);


-- -----------------------------------------------------------------------------
-- INJURIES  (from Transfermarkt)
--
-- injury_date is NOT NULL: the UNIQUE constraint on
-- (player_id, injury_date, injury_type) requires this to be effective.
-- PostgreSQL treats NULLs as distinct in unique indexes, so without NOT NULL
-- two rows with the same player_id and injury_type but NULL injury_date
-- would both insert successfully, creating silent duplicates.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS injuries (
    injury_id       SERIAL  PRIMARY KEY,
    player_id       INT     NOT NULL REFERENCES players (player_id) ON DELETE CASCADE,
    injury_type     TEXT,
    injury_date     DATE    NOT NULL,
    return_date     DATE,
    matches_missed  INT,
    season          TEXT,
    UNIQUE (player_id, injury_date, injury_type)
);

CREATE INDEX IF NOT EXISTS idx_injuries_player ON injuries (player_id);
CREATE INDEX IF NOT EXISTS idx_injuries_dates  ON injuries (injury_date, return_date);


-- -----------------------------------------------------------------------------
-- PLAYER MATCH STATS  (raw event aggregates, one row per player x match)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS player_match_stats (
    stat_id                 SERIAL  PRIMARY KEY,
    player_id               INT     NOT NULL REFERENCES players (player_id),
    match_id                INT     NOT NULL REFERENCES matches  (match_id),
    team_id                 INT             REFERENCES teams    (team_id),
    weather_id              INT             REFERENCES weather  (weather_id),

    result                  TEXT,

    goals                   INT     DEFAULT 0,
    assists                 INT     DEFAULT 0,
    shots                   INT     DEFAULT 0,
    xg                      FLOAT   DEFAULT 0,
    xa                      FLOAT   DEFAULT 0,
    key_passes              INT     DEFAULT 0,

    passes_attempted        INT     DEFAULT 0,
    passes_completed        INT     DEFAULT 0,
    pass_accuracy           FLOAT   DEFAULT 0,
    progressive_passes      INT     DEFAULT 0,

    carry_distance          FLOAT   DEFAULT 0,
    progressive_carries     INT     DEFAULT 0,

    dribbles_completed      INT     DEFAULT 0,

    tackles                 INT     DEFAULT 0,
    interceptions           INT     DEFAULT 0,
    clearances              INT     DEFAULT 0,
    pressures               INT     DEFAULT 0,

    yellow_cards            INT     DEFAULT 0,
    red_cards               INT     DEFAULT 0,

    minutes_played          INT     DEFAULT 0,
    sub_minute              INT,
    starting_position       TEXT,

    UNIQUE (player_id, match_id)
);

CREATE INDEX IF NOT EXISTS idx_pms_player       ON player_match_stats (player_id);
CREATE INDEX IF NOT EXISTS idx_pms_match        ON player_match_stats (match_id);
CREATE INDEX IF NOT EXISTS idx_pms_team         ON player_match_stats (team_id);
CREATE INDEX IF NOT EXISTS idx_pms_weather      ON player_match_stats (weather_id);
CREATE INDEX IF NOT EXISTS idx_pms_player_match ON player_match_stats (player_id, match_id);
CREATE INDEX IF NOT EXISTS idx_pms_team_match   ON player_match_stats (team_id,   match_id);


-- -----------------------------------------------------------------------------
-- PLAYER MATCH FEATURES  (computed ML columns, one row per player x match)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS player_match_features (
    feature_id              SERIAL  PRIMARY KEY,
    stat_id                 INT     NOT NULL UNIQUE REFERENCES player_match_stats (stat_id) ON DELETE CASCADE,
    player_id               INT     NOT NULL REFERENCES players (player_id),
    match_id                INT     NOT NULL REFERENCES matches  (match_id),

    matches_last_30_days    INT     DEFAULT 0,
    minutes_last_30_days    INT     DEFAULT 0,
    days_since_last_injury  INT,
    is_injured_next_30d     BOOLEAN DEFAULT FALSE,

    UNIQUE (player_id, match_id)
);

CREATE INDEX IF NOT EXISTS idx_pmf_stat   ON player_match_features (stat_id);
CREATE INDEX IF NOT EXISTS idx_pmf_player ON player_match_features (player_id);
CREATE INDEX IF NOT EXISTS idx_pmf_match  ON player_match_features (match_id);
CREATE INDEX IF NOT EXISTS idx_pmf_label  ON player_match_features (is_injured_next_30d)
    WHERE is_injured_next_30d = TRUE;


-- -----------------------------------------------------------------------------
-- PASS NETWORK EDGES
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pass_network_edges (
    edge_id         SERIAL  PRIMARY KEY,
    match_id        INT     NOT NULL REFERENCES matches  (match_id) ON DELETE CASCADE,
    team_id         INT             REFERENCES teams    (team_id),
    passer_id       INT             REFERENCES players  (player_id),
    receiver_id     INT             REFERENCES players  (player_id),
    pass_count      INT     DEFAULT 1,
    avg_x_start     FLOAT,
    avg_y_start     FLOAT,
    avg_x_end       FLOAT,
    avg_y_end       FLOAT,
    UNIQUE (match_id, team_id, passer_id, receiver_id)
);

-- -----------------------------------------------------------------------------
-- MATCH MINUTE SNAPSHOTS  (cumulative in-game stats per team, per minute)
-- Used by Model 5 in-game sub-model
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS match_minute_snapshots (
    snapshot_id         SERIAL  PRIMARY KEY,
    match_id            INT     NOT NULL REFERENCES matches (match_id) ON DELETE CASCADE,
    team_id             INT     NOT NULL REFERENCES teams   (team_id),
    minute              INT     NOT NULL,

    goals_so_far        INT     DEFAULT 0,
    xg_so_far           FLOAT   DEFAULT 0,
    shots_so_far        INT     DEFAULT 0,
    passes_so_far       INT     DEFAULT 0,
    pass_acc_so_far     FLOAT   DEFAULT 0,
    pressures_so_far    INT     DEFAULT 0,
    red_cards_so_far    INT     DEFAULT 0,

    UNIQUE (match_id, team_id, minute)
);

CREATE INDEX IF NOT EXISTS idx_mms_match       ON match_minute_snapshots (match_id);
CREATE INDEX IF NOT EXISTS idx_mms_match_team  ON match_minute_snapshots (match_id, team_id);
CREATE INDEX IF NOT EXISTS idx_mms_minute      ON match_minute_snapshots (minute);

CREATE INDEX IF NOT EXISTS idx_pne_match ON pass_network_edges (match_id);
CREATE INDEX IF NOT EXISTS idx_pne_team  ON pass_network_edges (match_id, team_id);


-- -----------------------------------------------------------------------------
-- VIEW: player age at time of match
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_player_match_age AS
SELECT
    pms.stat_id,
    pms.player_id,
    pms.match_id,
    m.match_date,
    p.date_of_birth,
    EXTRACT(YEAR FROM AGE(m.match_date, p.date_of_birth))::INT AS age_at_match
FROM player_match_stats pms
JOIN matches m ON m.match_id  = pms.match_id
JOIN players p ON p.player_id = pms.player_id
WHERE p.date_of_birth IS NOT NULL;