-- =============================================================================
-- Soccer Analytics ML System -- PostgreSQL Schema
--
-- ID naming convention (strict throughout):
--   *_id          internal surrogate PK generated by this DB (SERIAL)
--   sb_*_id       StatsBomb source identifier
--
-- StatsBomb-event-only platform. The Transfermarkt (injuries) and Open-Meteo
-- (weather) sources and their tables/columns were removed: they were never
-- populated for this dataset and the models that used them did not generalise.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- TEAMS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS teams (
    team_id         SERIAL  PRIMARY KEY,
    team_name       TEXT    NOT NULL,
    sb_team_id      INT     UNIQUE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_teams_sb ON teams (sb_team_id);


-- -----------------------------------------------------------------------------
-- PLAYERS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS players (
    player_id       SERIAL  PRIMARY KEY,
    sb_player_id    INT     UNIQUE,
    player_name     TEXT    NOT NULL,
    norm_name       TEXT
);

CREATE INDEX IF NOT EXISTS idx_players_sb        ON players (sb_player_id);
CREATE INDEX IF NOT EXISTS idx_players_norm_name ON players (norm_name);


-- -----------------------------------------------------------------------------
-- STADIUMS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stadiums (
    stadium_id      SERIAL  PRIMARY KEY,
    stadium_name    TEXT    NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_stadiums_name ON stadiums (stadium_name);


-- -----------------------------------------------------------------------------
-- MATCHES
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS matches (
    match_id        SERIAL  PRIMARY KEY,
    sb_match_id     INT     UNIQUE NOT NULL,
    match_date      DATE,
    home_team_id    INT     REFERENCES teams    (team_id),
    away_team_id    INT     REFERENCES teams    (team_id),
    home_score      INT,
    away_score      INT,
    competition     TEXT,
    season          TEXT,
    stadium_id      INT     REFERENCES stadiums (stadium_id)
);

CREATE INDEX IF NOT EXISTS idx_matches_date        ON matches (match_date);
CREATE INDEX IF NOT EXISTS idx_matches_competition ON matches (competition, season);
CREATE INDEX IF NOT EXISTS idx_matches_home_team   ON matches (home_team_id);
CREATE INDEX IF NOT EXISTS idx_matches_away_team   ON matches (away_team_id);
CREATE INDEX IF NOT EXISTS idx_matches_sb          ON matches (sb_match_id);
CREATE INDEX IF NOT EXISTS idx_matches_stadium     ON matches (stadium_id);


-- -----------------------------------------------------------------------------
-- PLAYER MATCH STATS  (raw event aggregates, one row per player x match)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS player_match_stats (
    stat_id                 SERIAL  PRIMARY KEY,
    player_id               INT     NOT NULL REFERENCES players (player_id),
    match_id                INT     NOT NULL REFERENCES matches  (match_id),
    team_id                 INT             REFERENCES teams    (team_id),

    result                  TEXT,

    goals                   INT     DEFAULT 0,
    assists                 INT     DEFAULT 0,
    shots                   INT     DEFAULT 0,
    xg                      FLOAT   DEFAULT 0,
    xa                      FLOAT   DEFAULT 0,
    key_passes              INT     DEFAULT 0,

    passes_attempted        INT     DEFAULT 0,
    passes_completed        INT     DEFAULT 0,
    pass_accuracy           FLOAT   DEFAULT 0,
    progressive_passes      INT     DEFAULT 0,

    carry_distance          FLOAT   DEFAULT 0,
    progressive_carries     INT     DEFAULT 0,

    dribbles_completed      INT     DEFAULT 0,

    tackles                 INT     DEFAULT 0,
    interceptions           INT     DEFAULT 0,
    clearances              INT     DEFAULT 0,
    pressures               INT     DEFAULT 0,

    yellow_cards            INT     DEFAULT 0,
    red_cards               INT     DEFAULT 0,

    minutes_played          INT     DEFAULT 0,
    sub_minute              INT,
    starting_position       TEXT,

    UNIQUE (player_id, match_id)
);

CREATE INDEX IF NOT EXISTS idx_pms_player       ON player_match_stats (player_id);
CREATE INDEX IF NOT EXISTS idx_pms_match        ON player_match_stats (match_id);
CREATE INDEX IF NOT EXISTS idx_pms_team         ON player_match_stats (team_id);
CREATE INDEX IF NOT EXISTS idx_pms_player_match ON player_match_stats (player_id, match_id);
CREATE INDEX IF NOT EXISTS idx_pms_team_match   ON player_match_stats (team_id,   match_id);


-- -----------------------------------------------------------------------------
-- PASS NETWORK EDGES
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pass_network_edges (
    edge_id         SERIAL  PRIMARY KEY,
    match_id        INT     NOT NULL REFERENCES matches  (match_id) ON DELETE CASCADE,
    team_id         INT             REFERENCES teams    (team_id),
    passer_id       INT             REFERENCES players  (player_id),
    receiver_id     INT             REFERENCES players  (player_id),
    pass_count      INT     DEFAULT 1,
    avg_x_start     FLOAT,
    avg_y_start     FLOAT,
    avg_x_end       FLOAT,
    avg_y_end       FLOAT,
    UNIQUE (match_id, team_id, passer_id, receiver_id)
);

-- -----------------------------------------------------------------------------
-- MATCH MINUTE SNAPSHOTS  (cumulative in-game stats per team, per minute)
-- Used by Model 5 in-game sub-model
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS match_minute_snapshots (
    snapshot_id         SERIAL  PRIMARY KEY,
    match_id            INT     NOT NULL REFERENCES matches (match_id) ON DELETE CASCADE,
    team_id             INT     NOT NULL REFERENCES teams   (team_id),
    minute              INT     NOT NULL,

    goals_so_far        INT     DEFAULT 0,
    xg_so_far           FLOAT   DEFAULT 0,
    shots_so_far        INT     DEFAULT 0,
    passes_so_far       INT     DEFAULT 0,
    pass_acc_so_far     FLOAT   DEFAULT 0,
    pressures_so_far    INT     DEFAULT 0,
    red_cards_so_far    INT     DEFAULT 0,

    UNIQUE (match_id, team_id, minute)
);

CREATE INDEX IF NOT EXISTS idx_mms_match       ON match_minute_snapshots (match_id);
CREATE INDEX IF NOT EXISTS idx_mms_match_team  ON match_minute_snapshots (match_id, team_id);
CREATE INDEX IF NOT EXISTS idx_mms_minute      ON match_minute_snapshots (minute);

CREATE INDEX IF NOT EXISTS idx_pne_match ON pass_network_edges (match_id);
CREATE INDEX IF NOT EXISTS idx_pne_team  ON pass_network_edges (match_id, team_id);


-- -----------------------------------------------------------------------------
-- shots: one row per Shot event, with geometry, context and freeze-frame
-- derived features. Powers the from-scratch xG model and shot maps.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shots (
    shot_id              SERIAL  PRIMARY KEY,
    sb_event_id          TEXT    UNIQUE NOT NULL,   -- StatsBomb event uuid
    match_id             INT     NOT NULL REFERENCES matches (match_id) ON DELETE CASCADE,
    player_id            INT              REFERENCES players (player_id),
    team_id              INT              REFERENCES teams   (team_id),
    minute               INT,

    -- geometry
    x                    FLOAT,   -- shot location (StatsBomb 120x80 pitch)
    y                    FLOAT,
    distance             FLOAT,   -- metres to goal centre
    angle                FLOAT,   -- radians subtended by the goal mouth

    -- context (categorical)
    body_part            TEXT,    -- Right Foot / Left Foot / Head / Other
    shot_type            TEXT,    -- Open Play / Free Kick / Penalty / Corner ...
    technique            TEXT,
    play_pattern         TEXT,
    under_pressure       BOOLEAN,
    first_time           BOOLEAN,

    -- freeze-frame derived
    defenders_in_cone    INT,     -- opponents inside the shot->goalposts triangle
    dist_to_nearest_def  FLOAT,
    gk_dist_to_goal      FLOAT,   -- keeper distance from goal centre
    gk_dist_to_shot      FLOAT,

    -- benchmark + label
    statsbomb_xg         FLOAT,   -- StatsBomb's own xG (validation benchmark only)
    is_goal              BOOLEAN NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_shots_match  ON shots (match_id);
CREATE INDEX IF NOT EXISTS idx_shots_player ON shots (player_id);
CREATE INDEX IF NOT EXISTS idx_shots_team   ON shots (team_id);